# Generated by Django 5.2.5 on 2026-05-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_campaign_media_campaign_nonwa_campaign_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vc_call_type',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vc_caller_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vc_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vc_plan_id',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vc_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VoiceMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voice_file_id', models.CharField(max_length=50)),
                ('media_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Campaign', max_length=255)),
                ('voice_file_id', models.CharField(blank=True, max_length=50)),
                ('caller_id', models.CharField(blank=True, max_length=20)),
                ('plan_id', models.CharField(default='2', max_length=10)),
                ('call_type', models.CharField(default='2', max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('invalid', models.IntegerField(default=0)),
                ('job_id', models.CharField(blank=True, max_length=100)),
                ('results', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_campaigns', to='api.user')),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.voicemediafile')),
            ],
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
