# Generated by Django 5.2.5 on 2026-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_credithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicecampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicemediafile',
            name='voice_file_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
