# Generated by Django 5.2.5 on 2026-05-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_voicecampaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicecampaign',
            old_name='invalid',
            new_name='nonwa',
        ),
    ]
