# Generated by Django 5.2.5 on 2026-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_invalid_voicecampaign_nonwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecampaign',
            name='retry_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicecampaign',
            name='retry_duration',
            field=models.IntegerField(default=0),
        ),
    ]
