# Generated by Django 5.2.5 on 2026-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_voicecampaign_retry_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemediafile',
            name='media_url',
        ),
        migrations.AddField(
            model_name='voicemediafile',
            name='audio_file',
            field=models.FileField(default='', upload_to='voice_files/'),
            preserve_default=False,
        ),
    ]
