# Generated by Django 5.2.5 on 2026-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_voicemediafile_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemediafile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_files/'),
        ),
    ]
