# Generated by Django 5.2.5 on 2026-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_voicemediafile_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemediafile',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='voicemediafile',
            name='media_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
