# Generated by Django 5.2.5 on 2026-06-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_voicemediafile_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemediafile',
            name='caller_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
