# Generated by Django 5.2.5 on 2026-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_voicemediafile_caller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecampaign',
            name='busy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicecampaign',
            name='no_answer',
            field=models.IntegerField(default=0),
        ),
    ]
