# Generated by Django 5.2.5 on 2026-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_voicecampaign_busy_voicecampaign_no_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemediafile',
            name='caller_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='voicemediafile',
            name='media_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voicemediafile',
            name='voice_file_id',
            field=models.TextField(default=''),
        ),
    ]
