# Generated by Django 5.2.5 on 2026-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_voicemediafile_caller_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecampaign',
            name='caller_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='voicecampaign',
            name='job_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voicecampaign',
            name='voice_file_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voicemediafile',
            name='caller_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
